version: '3.9'

services:
  sqlserver:
    container_name: sqlserver-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    working_dir: /usr/src/app
    command: sh -c 'chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pwd@1234!"

  postgree:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Pwd@1234!

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080