// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SEFAC.Infrastructure.Persistence;

#nullable disable

namespace SEFAC.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231106134556_Correcao-relacionamentos")]
    partial class Correcaorelacionamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SEFAC.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Cod_Curso");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("NumeroMatricula")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nr_Matricula");

                    b.HasKey("Id");

                    b.HasIndex("NumeroMatricula")
                        .IsUnique();

                    b.ToTable("Aluno", (string)null);
                });

            modelBuilder.Entity("SEFAC.Domain.Entities.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Base64PDF")
                        .HasColumnType("text")
                        .HasColumnName("Anexo");

                    b.Property<string>("CodigoSiex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Cd_siex");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Atividade", (string)null);
                });

            modelBuilder.Entity("SEFAC.Domain.Entities.ExecucoesAtividades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CargaHoraria")
                        .HasColumnType("numeric")
                        .HasColumnName("Carga_Horaria");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Dt_Fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Dt_Inicio");

                    b.Property<decimal>("Duracao")
                        .HasColumnType("numeric")
                        .HasColumnName("Duracao");

                    b.Property<int>("IdAluno")
                        .HasColumnType("integer");

                    b.Property<int>("IdAtividade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdAtividade");

                    b.ToTable("ExecucaoAtividade", (string)null);
                });

            modelBuilder.Entity("SEFAC.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Senha");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("SEFAC.Domain.Entities.ExecucoesAtividades", b =>
                {
                    b.HasOne("SEFAC.Domain.Entities.Aluno", "Aluno")
                        .WithMany("ExecucaoAtividades")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("SEFAC.Domain.Entities.Atividade", "Atividade")
                        .WithMany("Execucoes")
                        .HasForeignKey("IdAtividade")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("SEFAC.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("ExecucaoAtividades");
                });

            modelBuilder.Entity("SEFAC.Domain.Entities.Atividade", b =>
                {
                    b.Navigation("Execucoes");
                });
#pragma warning restore 612, 618
        }
    }
}
