// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEFAC.Infrastructure.Persistence;

#nullable disable

namespace SEFAC.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SEFAC.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Cod_Curso");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<string>("NumeroMatricula")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Nr_Matricula");

                    b.HasKey("Id");

                    b.HasIndex("NumeroMatricula")
                        .IsUnique();

                    b.ToTable("Aluno", (string)null);
                });

            modelBuilder.Entity("SEFAC.Domain.Entities.ExecucoesAtividades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("CargaHoraria")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Carga_Horaria");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Dt_Fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Dt_Inicio");

                    b.Property<decimal>("Duracao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Duracao");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdAluno");

                    b.ToTable("Atividade", (string)null);
                });

            modelBuilder.Entity("SEFAC.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Senha");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("SEFAC.Domain.Entities.ExecucoesAtividades", b =>
                {
                    b.HasOne("SEFAC.Domain.Entities.Aluno", "Aluno")
                        .WithMany("ExecucoesAtividades")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("SEFAC.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("ExecucoesAtividades");
                });
#pragma warning restore 612, 618
        }
    }
}
